### ISSUE TITLE
Created QR code for Questionaire 

### ISSUE THREAD

**Issue by AndrewMarcil** [CWWhitney/ethnoforestry_agroforestry#8]
![qrcode](https://github.com/CWWhitney/ethnoforestry_agroforestry/assets/141144042/d359c5ac-5d3f-4fba-a30c-1dadbf5c8cd5)

**Comment by CWWhitney** [comment]
Share the url too @andrewm1234

**Comment by AndrewMarcil** [comment]
https://docs.google.com/forms/d/12d2q166-dQ8rmn4o3NxQHXXOMlGvyavIxPYjegBnlvw/edit

**Comment by CWWhitney** [comment]
Great work 
I think we need to regroup and think about how to steer people to appropriate questions - something like the 'go to section' option - possibly after each section? 

![Screenshot 2024-05-15 at 9 44 25 AM](https://github.com/CWWhitney/ethnoforestry_agroforestry/assets/19190662/b7017a75-f247-4470-b52e-c41da36bec4a)

**Comment by CWWhitney** [comment]
Completed
